import { useMemo, useState } from 'react';
import Sidebar from './components/Sidebar';
import MetricCard from './components/MetricCard';
import Board from './components/Board';
import ActivityTimeline from './components/ActivityTimeline';
import CommandPalette from './components/CommandPalette';
import { activities, workstreams } from './data';
import type { Workstream } from './types';

export default function App() {
  const [active, setActive] = useState('Overview');
  const [commandOpen, setCommandOpen] = useState(false);
  const [selected, setSelected] = useState<Workstream | null>(null);
  const [filter, setFilter] = useState<'All'|'At risk'>('All');
  const visible = useMemo(() => filter === 'All' ? workstreams : workstreams.filter(item => item.status === 'At risk'), [filter]);
  return <div className="app-shell"><Sidebar active={active} onNavigate={setActive} /><main className="main-content"><header className="topbar"><div className="breadcrumb"><span>Product Studio</span><span>/</span><strong>{active}</strong></div><div className="topbar-actions"><button className="search-trigger" onClick={()=>setCommandOpen(true)}><span>⌕</span> Search <kbd>⌘ K</kbd></button><button className="notification-button" aria-label="Notifications">♢<span className="notification-dot" /></button><button className="avatar avatar-purple">RG</button></div></header><div className="page-content"><section className="hero"><div><div className="eyebrow">MONDAY, SEPTEMBER 21, 2026</div><h1>Good morning, Rahul<span className="wave">✦</span></h1><p>Here is the shape of your work today. Focus on what needs a decision.</p></div><button className="primary-button" onClick={()=>setCommandOpen(true)}>＋ New workstream</button></section><section className="metrics-grid"><MetricCard label="Momentum score" value="82" trend="↑ 12% from last week" /><MetricCard label="Workstreams moving" value="08 / 10" trend="2 need attention" tone="warning" /><MetricCard label="Decisions captured" value="24" trend="↑ 6 this week" /><MetricCard label="Team focus" value="91%" trend="Healthy signal" tone="neutral" /></section><section className="content-grid"><div className="primary-column"><div className="filter-row"><div><button className={`filter-button ${filter==='All'?'selected':''}`} onClick={()=>setFilter('All')}>All workstreams <span>8</span></button><button className={`filter-button ${filter==='At risk'?'selected':''}`} onClick={()=>setFilter('At risk')}>At risk <span>2</span></button></div><button className="view-toggle">▦ <span>List view</span>⌄</button></div><Board items={visible} onSelect={setSelected} /></div><ActivityTimeline activities={activities} /></section></div></main><CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} />{selected && <div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="detail-modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">WORKSTREAM DETAIL</span><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><p className="modal-description">Owned by {selected.owner}. This focused view is the starting point for connecting a real workstream API to the interface.</p><div className="detail-stats"><div><small>STATUS</small><strong>{selected.status}</strong></div><div><small>PRIORITY</small><strong>{selected.priority}</strong></div><div><small>PROGRESS</small><strong>{selected.progress}%</strong></div></div><div className="modal-footer"><button className="ghost-button" onClick={()=>setSelected(null)}>Close</button><button className="primary-button" onClick={()=>setSelected(null)}>Mark reviewed</button></div></div></div>}</div>;
}
